### ISSUE TITLE
Present function name in black

### ISSUE THREAD

**Issue by hagenw** [audeering/sphinx-audeering-theme#49]
As discussed in https://github.com/audeering/sphinx-audeering-theme/issues/46#issuecomment-993588987

we would like to change

![image](https://user-images.githubusercontent.com/173624/146018099-e5ce4f01-197f-4b78-bbe7-0739bfa52f0d.png)

to

![image](https://user-images.githubusercontent.com/173624/146018173-4dbe5648-dc99-404a-b02d-bf74b528b3cc.png)

**Comment by drux007** [comment]
What about changing it other way around? Present function name in **red** and the function arguments in black?

The red colour represents something more important and the function name is more important than its arguments.

If not, I always support changing the function name in another color since it's more readable.

**Comment by hagenw** [comment]
Closed by #51
